### LOGIN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "userName": "yourusername",
  "password": "mypassword"
}

@after
> {% client.globalSet("loggedIn", true) %}

### USERS API ###
### Get all users
GET http://localhost:3000/api/users/

### Get user by username
GET http://localhost:3000/api/users/yourusername

### Update user by username
PUT http://localhost:3000/api/users/yourusername
Content-Type: application/json

{
  "firstName": "JosephUpdated",
  "lastName": "Smith",
  "email": "joesmith@byui.edu"
}

### TRIPS API ###
### Get all trips for logged-in user
GET http://localhost:3000/api/trips/

### Get trip by title (existing trip)
GET http://localhost:3000/api/trips?tripTitle=Honeymoon&userName=yourusername

### Create a new trip
POST http://localhost:3000/api/trips/
Content-Type: application/json

{
  "tripTitle": "Automation Test Trip",
  "startDate": "01/01/2030",
  "endDate": "01/10/2030",
  "description": "Trip created by automated test",
  "totalCost": 1000
}

@after
> {% client.globalSet("tripId", response._id) %}

### DESTINATIONS API ###
### Get all destinations for logged-in user
GET http://localhost:3000/api/destinations/

### Get destinations by tripTitle
GET http://localhost:3000/api/destinations?tripTitle=Honeymoon&userName=yourusername

### Create a new destination
POST http://localhost:3000/api/destinations/
Content-Type: application/json

{
  "tripTitle": "Automation Test Trip",
  "userName": "yourusername",
  "locationName": "Test Beach",
  "notes": ["Relax", "Fun"]
}

@after
> {% client.globalSet("destinationId", response._id) %}

### ACTIVITIES API ###
### Get all activities for logged-in user
GET http://localhost:3000/api/activities/

### Get activities by tripTitle
GET http://localhost:3000/api/activities?tripTitle=Honeymoon&userName=yourusername

### Create a new activity
POST http://localhost:3000/api/activities/
Content-Type: application/json

{
  "tripTitle": "Automation Test Trip",
  "userName": "yourusername",
  "locationName": "Test Beach",
  "activityName": "Test Parasailing",
  "date": "01/02/2030",
  "time": "10:00 AM",
  "cost": 200
}

@after
> {% client.globalSet("activityId", response._id) %}